import os
import uuid
import logging
from pptx import Presentation
from fpdf import FPDF

logger = logging.getLogger(__name__)

class ExportEngine:
    """ Manages the creation of PRDs, DRDs, and Slide Decks from Architecture Outputs. """
    
    def __init__(self):
        self.exports_dir = "data/exports"
        os.makedirs(self.exports_dir, exist_ok=True)
        
    def generate_prd_pdf(self, architecture_data: dict) -> str:
        """ Generates a PRD/TRD combined PDF file with full system details. """
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # Title
            pdf.set_font("helvetica", "B", 20)
            pdf.cell(0, 15, txt="System Architecture Document (PRD/TRD)", ln=True, align='C')
            pdf.ln(5)
            
            # Metadata
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, txt=f"Requirement Summary: {architecture_data.get('requirement', 'N/A')}", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.cell(0, 10, txt=f"Generated At: {architecture_data.get('created_at', 'TBD')}", ln=True)
            pdf.ln(5)

            # Components
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 10, txt="1. System Components", ln=True)
            pdf.set_font("helvetica", "", 10)
            for comp in architecture_data.get("components", []):
                pdf.set_font("helvetica", "B", 11)
                pdf.cell(0, 8, txt=f"- {comp.get('name')} ({comp.get('type')})", ln=True)
                pdf.set_font("helvetica", "", 10)
                pdf.multi_cell(0, 6, txt=f"  Tech: {comp.get('technology')}\n  Role: {comp.get('description')}\n  Responsibilities: {comp.get('responsibilities')}")
                pdf.ln(2)

            # ADRs
            pdf.add_page()
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 10, txt="2. Architectural Decision Records (ADR)", ln=True)
            for adr in architecture_data.get("adrs", []):
                pdf.set_font("helvetica", "B", 11)
                pdf.cell(0, 8, txt=f"- [{adr.get('status').upper()}] {adr.get('title')}", ln=True)
                pdf.set_font("helvetica", "", 10)
                pdf.multi_cell(0, 6, txt=f"  Decision: {adr.get('decision')}\n  Rationale: {adr.get('rationale')}\n  Consequences: {adr.get('consequences')}")
                pdf.ln(4)

            # Failure Modes
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 10, txt="3. Failure Modes & Mitigation", ln=True)
            for fm in architecture_data.get("failure_modes", []):
                pdf.set_font("helvetica", "B", 11)
                pdf.cell(0, 8, txt=f"- {fm.get('component')}: {fm.get('failure_type')}", ln=True)
                pdf.set_font("helvetica", "", 10)
                pdf.cell(0, 6, txt=f"  Probability: {fm.get('probability')} | Impact: {fm.get('impact')}", ln=True)
                pdf.multi_cell(0, 6, txt=f"  Mitigation: {fm.get('mitigation')}")
                pdf.ln(2)

            # Phases
            pdf.ln(5)
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 10, txt="4. Implementation Phases", ln=True)
            for phase in architecture_data.get("phases", []):
                pdf.cell(0, 8, txt=f"- {phase.get('name')} ({phase.get('status')})", ln=True)

            file_path = f"{self.exports_dir}/architecture_docs_{uuid.uuid4().hex[:8]}.pdf"
            pdf.output(file_path)
            return file_path
        except Exception as e:
            logger.error(f"Failed to generate PDF: {e}")
            return ""
        
    def generate_architecture_slides(self, architecture_data: dict) -> str:
        """ Generates a .pptx slide deck representation of the architecture. """
        try:
            prs = Presentation()
            
            # 1. Title Slide
            slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = "Architecture Design Proposal"
            slide.placeholders[1].text = f"Requirement: {architecture_data.get('requirement', 'TBD')}\nGenerated by ELDER Agent"
            
            # 2. Components Slide
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = "System Components"
            tf = slide.placeholders[1].text_frame
            for comp in architecture_data.get("components", [])[:5]: # Cap at 5 for slide space
                p = tf.add_paragraph()
                p.text = f"{comp.get('name')}: {comp.get('technology')}"
                p.level = 0
            
            # 3. Key Decisions (ADRs)
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = "Key Decisions (ADR)"
            tf = slide.placeholders[1].text_frame
            for adr in architecture_data.get("adrs", [])[:3]:
                p = tf.add_paragraph()
                p.text = adr.get('title')
                p.level = 0
                p = tf.add_paragraph()
                p.text = adr.get('decision')
                p.level = 1

            # 4. Failure Modes
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = "Risks & Mitigations"
            tf = slide.placeholders[1].text_frame
            for fm in architecture_data.get("failure_modes", [])[:3]:
                p = tf.add_paragraph()
                p.text = f"Risk: {fm.get('component')} - {fm.get('failure_type')}"
                p.level = 0
            
            file_path = f"{self.exports_dir}/architecture_deck_{uuid.uuid4().hex[:8]}.pptx"
            prs.save(file_path)
            return file_path
        except Exception as e:
            logger.error(f"Failed to generate PPTX: {e}")
            return ""

export_engine = ExportEngine()
