-- Seed data: 30 reference architectures
INSERT INTO memory (category, content, metadata) VALUES
('architecture', 'Microservices Architecture - Decompose applications into small, autonomous services that communicate via APIs', '{"domain": "distributed_systems", "scalability": "high", "complexity": "medium"}'),
('architecture', 'Event-Driven Architecture - Services communicate through asynchronous event messages using message brokers', '{"domain": "reactive_systems", "scalability": "high", "complexity": "high"}'),
('architecture', 'Layered Architecture - Organize code into layers (presentation, business logic, data access)', '{"domain": "traditional", "scalability": "low", "complexity": "low"}'),
('architecture', 'Hexagonal Architecture - Ports and adapters pattern for clean separation of concerns', '{"domain": "clean_code", "scalability": "medium", "complexity": "medium"}'),
('architecture', 'CQRS - Command Query Responsibility Segregation - Separate read and write operations', '{"domain": "domain_driven", "scalability": "high", "complexity": "medium"}'),
('architecture', 'Event Sourcing - Store state changes as a sequence of events instead of current state', '{"domain": "domain_driven", "scalability": "medium", "complexity": "high"}'),
('architecture', 'Serverless Architecture - Run code without managing servers using FaaS platforms', '{"domain": "cloud_native", "scalability": "high", "complexity": "low"}'),
('architecture', 'GraphQL Federation - Compose multiple GraphQL services into one unified graph', '{"domain": "api_design", "scalability": "high", "complexity": "medium"}'),
('architecture', 'API Gateway Pattern - Single entry point for all client requests', '{"domain": "api_design", "scalability": "high", "complexity": "low"}'),
('architecture', 'Saga Pattern - Manage distributed transactions across services', '{"domain": "distributed_systems", "scalability": "medium", "complexity": "high"}'),
('technology', 'PostgreSQL - Advanced open source relational database with JSON support', '{"type": "database", "category": "relational"}'),
('technology', 'Redis - In-memory data structure store for caching and messaging', '{"type": "cache", "category": "nosql"}'),
('technology', 'Apache Kafka - Distributed event streaming platform', '{"type": "messaging", "category": "stream_processing"}'),
('technology', 'Nginx - High-performance web server and reverse proxy', '{"type": "gateway", "category": "load_balancer"}'),
('technology', 'Docker - Container platform for packaging applications', '{"type": "containerization", "category": "devops"}'),
('technology', 'Kubernetes - Container orchestration for managing containerized workloads', '{"type": "orchestration", "category": "devops"}'),
('technology', 'GraphQL - Query language for APIs with type system', '{"type": "api", "category": "query"}'),
('technology', 'gRPC - High-performance RPC framework using HTTP/2', '{"type": "api", "category": "rpc"}'),
('technology', 'Elasticsearch - Distributed search and analytics engine', '{"type": "search", "category": "nosql"}'),
('technology', 'Prometheus - Open-source monitoring and alerting toolkit', '{"type": "monitoring", "category": "observability"}'),
('pattern', 'Circuit Breaker - Prevent cascading failures by failing fast', '{"domain": "resilience", "complexity": "low"}'),
('pattern', 'Bulkhead - Isolate resources to prevent cross-contamination', '{"domain": "resilience", "complexity": "low"}'),
('pattern', 'Retry Pattern - Automatic retry for transient failures', '{"domain": "resilience", "complexity": "low"}'),
('pattern', 'Cache-Aside - Application manages cache population', '{"domain": "caching", "complexity": "low"}'),
('pattern', 'Sharding - Horizontal partitioning of data across databases', '{"domain": "scaling", "complexity": "high"}'),
('pattern', 'Blue-Green Deployment - Zero-downtime deployment strategy', '{"domain": "deployment", "complexity": "medium"}'),
('pattern', 'Canary Release - Gradual rollout to subset of users', '{"domain": "deployment", "complexity": "medium"}'),
('pattern', 'Strangler Fig - Incrementally migrate legacy systems', '{"domain": "migration", "complexity": "high"}'),
('pattern', 'Anti-Corruption Layer - Translate between legacy and new systems', '{"domain": "integration", "complexity": "medium"}'),
('pattern', 'Sidecar - Deploy helper components alongside main service', '{"domain": "deployment", "complexity": "medium"}');
